// Shared stat definitions used across public, free, and premium tiers.

export type PublicOffenseFields =
  | "plays"
  | "total_yards"
  | "yards_per_play"
  | "epa_per_play"
  | "success_rate"
  | "explosive_play_rate"
  | "pass_plays"
  | "run_plays"
  | "pass_rate"
  | "rush_rate"
  | "pass_yards"
  | "rush_yards"
  | "pass_yards_per_game"
  | "rush_yards_per_game"
  | "third_down_att"
  | "third_down_conv"
  | "third_down_pct"
  | "red_zone_trips"
  | "red_zone_td_pct"
  | "turnovers"
  | "sacks_taken";

export type PublicDefenseFields =
  | "plays_defended"
  | "yards_allowed"
  | "yards_per_play_allowed"
  | "epa_per_play_allowed"
  | "success_rate_allowed"
  | "explosive_play_rate_allowed"
  | "pass_yards_allowed"
  | "rush_yards_allowed"
  | "pass_yards_per_game_allowed"
  | "rush_yards_per_game_allowed"
  | "third_down_att_def"
  | "third_down_conv_def"
  | "third_down_pct_def"
  | "sacks_made"
  | "takeaways"
  | "points_allowed";

export type PublicSpecialFields =
  | "punt_returns"
  | "punt_return_avg"
  | "kick_returns"
  | "kick_return_avg"
  | "punt_yards"
  | "punt_avg"
  | "punt_net_avg"
  | "field_goals_made"
  | "field_goals_att"
  | "field_goal_pct";

// Hidden but filterable fields for free logged-in users
export type HiddenFilterFields =
  | "quarter"
  | "clock"
  | "down"
  | "distance"
  | "yard_line"
  | "start_yardline"
  | "score_diff"
  | "score_diff_bucket"
  | "hashmark"
  | "field_side"
  | "shotgun"
  | "no_huddle"
  | "play_action"
  | "rpo"
  | "motion"
  | "run_direction"
  | "run_gap"
  | "pass_depth_bucket"
  | "pass_location"
  | "qb_scramble"
  | "qb_hit"
  | "pressure"
  | "blitz"
  | "sack"
  | "home_away"
  | "score_state"
  | "red_zone"
  | "goal_to_go"
  | "two_minute"
  | "personnel_offense"
  | "personnel_defense"
  | "rbs"
  | "tes"
  | "wrs"
  | "dls"
  | "lbs"
  | "dbs";

// Premium enriched fields
export type PremiumEnrichedFields =
  | "en_coverage_single_high"
  | "en_coverage_two_high"
  | "en_coverage_zero"
  | "en_coverage_quarters"
  | "en_coverage_match"
  | "en_ngs_off_formation"
  | "en_motion_type"
  | "en_motion_at_snap"
  | "en_shift"
  | "en_align_str"
  | "en_rbs"
  | "en_tes"
  | "en_wrs"
  | "en_block_scheme"
  | "en_pass_rush_pressure"
  | "en_route_type"
  | "en_air_yards"
  | "en_yac"
  | "en_targeted_receiver"
  | "en_read_progression"
  | "en_run_gap"
  | "en_run_scheme"
  | "en_run_support_fit"
  | "en_pressure_type"
  | "en_pass_rush_scheme"
  | "en_box_count"
  | "en_def_front";

// Premium derived advanced metrics
export type PremiumDerivedMetrics =
  | "coverage_success_rate"
  | "epa_vs_man"
  | "epa_vs_zone"
  | "completion_pct_by_coverage"
  | "explosive_pct_by_coverage"
  | "pressure_rate"
  | "pressure_success_rate"
  | "epa_by_personnel"
  | "success_rate_by_personnel"
  | "play_action_rate_by_formation";
